name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  RELEASE_BIN: vsr-new
  RELEASE_ADDS: README.md LICENSE

jobs: 
  build:
    name: Build release

    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            suffix: amd64
          - build: macos
            os: macos-latest
            rust: stable
            suffix: darwin
          - build: windows
            os: windows-latest
            rust: stable
            suffix: w32-64


    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        if: matrix.os != 'macos-latest'
        with:
          toolchain: stable
          default: true
          override: true

      - name: Rust toolchain - macos
        uses: actions-rs/toolchain@v1
        if: matrix.os == 'macos-latest'
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build project
        if: matrix.os != 'windows-latest'
        run: cargo build --all --release && strip target/release/${{ env.RELEASE_BIN }} && mv target/release/${{ env.RELEASE_BIN }} target/release/${{ env.RELEASE_BIN }}_${{ matrix.suffix }}
      
      - name: Build project - windows
        if: matrix.os == 'windows-latest'
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.os != 'windows-latest'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/${{ env.RELEASE_BIN }}_${{ matrix.suffix }}
      
      - name: Release - windows
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/${{ env.RELEASE_BIN }}.exe
